// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace CountriesApp
{
	public partial class DetailViewController : UIViewController
	{
		DBLayer layer = new DBLayer();
		public DetailViewController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();
			this.NavigationItem.Title = "Details";
			this.EdgesForExtendedLayout = UIRectEdge.None;
		}

		public override void ViewWillAppear (bool animated)
		{
			base.ViewWillAppear (animated);
			var data = layer.FindCountry (Constants.CountryCode);
			if (data != null) {
				CountryImage.Image = UIImage.FromBundle ("Countries/" + Constants.CountryCode);
				CountryName.Text = "Country Name : " + Constants.CountryCode + " - " + data.CountryName;
				CountryCurrency.Text = "Currency : " + data.Currency;
				CountryPhoneCode.Text = "Phone Code : +" + data.PhoneCode;
			}

			BtnAddFavorites.TouchUpInside += (object sender, EventArgs e) => {
				if(layer.FindFavorite(Constants.CountryCode) == null) {
					AddToFavorites favorites = new  AddToFavorites();
					favorites.CountryCode = Constants.CountryCode;
					favorites.CountryName = data.CountryName;
					favorites.Currency = data.Currency;
					favorites.PhoneCode = data.PhoneCode;
					layer.AddToFavorites (favorites);
					var controller = UIAlertController.Create("Add To Favorites", 
						"Country Code " + Constants.CountryCode + " has added as favorite", 
						UIAlertControllerStyle.Alert);
					controller.AddAction (UIAlertAction.Create ("Ok", UIAlertActionStyle.Default, null));
					PresentViewController (controller, true, null);
				}
				else {
					var controller = UIAlertController.Create("Add To Favorites", 
						"Country Code " + Constants.CountryCode + " has already added as favorite", 
						UIAlertControllerStyle.Alert);
					controller.AddAction (UIAlertAction.Create ("Ok", UIAlertActionStyle.Default, null));
					PresentViewController (controller, true, null);
					
				}
			};
		}
	}
}
